name: Run ascendev actions

on:
 push:
   branches: ["main"]

jobs:
  ascendev:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    name: Check pull requests
    
    steps:
      - name: Check out project
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Run custom action
        uses: tamerlantian01/docker-action-test@v2.0.2
        with:
          base-url: 'https://6fa0-2800-484-d38e-a200-6595-4ab-f075-3bb6.ngrok-free.app/api/v1'
